# Generated by Django 5.2.8 on 2025-11-11 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, null=True)),
                ('tanto', models.CharField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitsumori_request_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('drawing_data', models.FileField(blank=True, null=True, upload_to='uploads/drawing/<django.db.models.fields.related.ForeignKey>', verbose_name='<django.db.models.fields.related.ForeignKey><built-in function id>')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='Lists.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('drawing_num', models.CharField(db_index=True, max_length=50)),
                ('material', models.CharField(blank=True, choices=[('SUS304', 'SUS304'), ('SUS303', 'SUS303'), ('SUS316', 'SUS316'), ('SUS440C', 'SUS440C'), ('SS400', 'SS400'), ('S45C', 'S45C'), ('S50C', 'S50C'), ('SCM435', 'SCM435'), ('SUJ2', 'SUJ2'), ('SPHC', 'SPHC'), ('SPCC', 'SPCC')], null=True)),
                ('surface', models.CharField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, null=True)),
                ('contractor_price', models.IntegerField(blank=True, null=True)),
                ('agree_price', models.IntegerField(blank=True, null=True)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='Lists.cases')),
            ],
        ),
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, null=True)),
                ('tanto', models.CharField(blank=True, null=True)),
                ('mail', models.CharField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('bad', 'Bad')], null=True)),
                ('sheet', models.BooleanField(default=False)),
                ('cut', models.BooleanField(default=False)),
                ('can', models.BooleanField(default=False)),
                ('coat', models.BooleanField(default=False)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractors', to='Lists.products')),
            ],
        ),
    ]
