# Generated by Django 5.2.7 on 2025-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(choices=[('アサノ・マシン・エース', 'アサノ・マシン・エース'), ('辰山製作所', '辰山製作所')], db_index=True)),
                ('mitsumori_request_date', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
