# Generated by Django 5.2.7 on 2025-10-24 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cases',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lists.customers'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_num', models.CharField(db_index=True, max_length=50)),
                ('drawing_data', models.FileField(upload_to='uploads/drawing/', verbose_name=models.CharField(db_index=True, max_length=50))),
                ('surface', models.CharField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, null=True)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lists.cases')),
            ],
        ),
    ]
