# Generated by Django 5.2.8 on 2025-11-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractors',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='contractor_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price', to='Lists.contractors'),
        ),
    ]
