# Generated by Django 5.2.8 on 2025-11-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0002_alter_contractors_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='contractor_price',
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price', to='Lists.products')),
                ('price_contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_contractor', to='Lists.contractors')),
            ],
        ),
    ]
