# Generated by Django 5.2.7 on 2025-10-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0002_contractors_customers_alter_cases_customer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='drawing_data',
        ),
        migrations.AddField(
            model_name='cases',
            name='drawing_data',
            field=models.FileField(blank=True, null=True, upload_to='uploads/drawing/<django.db.models.fields.related.ForeignKey>', verbose_name='<django.db.models.fields.related.ForeignKey><built-in function id>'),
        ),
    ]
