# Generated by Django 5.2.7 on 2025-10-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0003_remove_products_drawing_data_cases_drawing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='drawing_data',
            field=models.FileField(upload_to='uploads/drawing/<django.db.models.fields.related.ForeignKey>', verbose_name='<django.db.models.fields.related.ForeignKey><built-in function id>'),
        ),
    ]
