# Generated by Django 5.2.8 on 2025-11-11 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0003_remove_products_contractor_price_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='Lists.products'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
