# Generated by Django 5.2.8 on 2025-11-11 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0004_prices_product_alter_prices_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='price_contractor',
        ),
        migrations.AddField(
            model_name='prices',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='Lists.contractors'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_product', to='Lists.products'),
        ),
    ]
