# Generated by Django 5.2.8 on 2025-11-11 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0005_remove_prices_price_contractor_prices_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_case', to='Lists.cases'),
        ),
    ]
