# Generated by Django 5.2.8 on 2025-11-11 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0006_prices_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='case',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='product',
        ),
        migrations.AddField(
            model_name='cases',
            name='contractor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='Lists.contractors'),
        ),
        migrations.AddField(
            model_name='prices',
            name='contractor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_price', to='Lists.contractors'),
        ),
        migrations.AddField(
            model_name='prices',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_price', to='Lists.products'),
        ),
    ]
