# Generated by Django 5.2.8 on 2025-11-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0007_remove_prices_case_remove_prices_contractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='contractor_id',
        ),
        migrations.RemoveField(
            model_name='cases',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='contractor_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='num',
        ),
        migrations.AddField(
            model_name='cases',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_case', to='Lists.customers'),
        ),
        migrations.AddField(
            model_name='products',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_product', to='Lists.cases'),
        ),
        migrations.CreateModel(
            name='Gaityus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_gaityu', to='Lists.cases')),
                ('contractor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_gaityu', to='Lists.contractors')),
            ],
        ),
        migrations.AddField(
            model_name='prices',
            name='gaityu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractor_gaityu', to='Lists.gaityus'),
        ),
    ]
