# Generated by Django 5.2.8 on 2025-11-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0008_remove_cases_contractor_id_remove_cases_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_case', to='Lists.customers'),
        ),
        migrations.AlterField(
            model_name='gaityus',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_gaityu', to='Lists.cases'),
        ),
        migrations.AlterField(
            model_name='gaityus',
            name='contractor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_gaityu', to='Lists.contractors'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='gaityu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_gaityu', to='Lists.gaityus'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='Lists.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_product', to='Lists.cases'),
        ),
    ]
