# Generated by Django 5.2.8 on 2025-11-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0009_alter_cases_customer_id_alter_gaityus_case_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='gaityu_id',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='product_id',
        ),
        migrations.AddField(
            model_name='prices',
            name='gaityu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_gaityu', to='Lists.gaityus'),
        ),
        migrations.AddField(
            model_name='prices',
            name='pk',
            field=models.CompositePrimaryKey('product_id', 'gaityu_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='Lists.products'),
        ),
    ]
