# Generated by Django 5.2.8 on 2025-11-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0010_remove_prices_gaityu_id_remove_prices_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaityus',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='gaityus',
            old_name='contractor_id',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='pk',
        ),
        migrations.AddField(
            model_name='prices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='gaityu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_gaityu', to='Lists.gaityus'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='Lists.products'),
        ),
    ]
