# Generated by Django 5.2.8 on 2025-11-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0011_rename_case_id_gaityus_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.CharField(blank=True, null=True),
        ),
    ]
