# Generated by Django 5.2.8 on 2025-11-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0012_alter_prices_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='cases',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='Lists.customers'),
        ),
        migrations.AlterField(
            model_name='gaityus',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaityu', to='Lists.cases'),
        ),
        migrations.AlterField(
            model_name='gaityus',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaityu', to='Lists.contractors'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='gaityu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='Lists.gaityus'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='Lists.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Lists.cases'),
        ),
    ]
