# Generated by Django 5.2.8 on 2025-11-13 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0013_remove_cases_customer_id_cases_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaityus',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaityus', to='Lists.cases'),
        ),
        migrations.AlterField(
            model_name='gaityus',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaityus', to='Lists.contractors'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='gaityu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Lists.gaityus'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Lists.products'),
        ),
    ]
