# Generated by Django 5.2.8 on 2025-11-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0014_alter_gaityus_case_alter_gaityus_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaityus',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaityus', to='Lists.products'),
        ),
    ]
