# Generated by Django 5.2.8 on 2025-11-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lists', '0015_gaityus_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaityus',
            name='product',
        ),
    ]
